#! /bin/bash

QUESTION=$1

INPUT="{\"input\":\"${QUESTION}\",\"collection_name\":\"default\" }"
echo 
curl --header "Content-Type: application/json" -d "${INPUT}" localhost:8002/query/ | jq .results

